services:
  lab-runner:
    image: jupyter/base-notebook:latest
    volumes:
      - ../..:/workspaces:cached
    user: "1000:100"

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  mongodb:
    profiles: ["local-mongodb"]
    image: mongodb/mongodb-atlas-local:latest
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=mongodb
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
